sudo: required
services:
  - docker

before_install:
  - docker build -t wptalento/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wptalento/react-test npm test -- --coverage

after_success:
  - docker build -t wptalento/multi-client ./client
  - docker build -t wptalento/multi-nginx ./nginx
  - docker build -t wptalento/multi-server ./server
  - docker build -t wptalento/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push wptalento/multi-client
  - docker push wptalento/multi-nginx
  - docker push wptalento/multi-server
  - docker push wptalento/multi-worker

